export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const GET_RECIPE = "GET_RECIPE";
export const CLEAR_RECIPES = "CLEAR_RECIPES";
export const ADD_RECIPES = "ADD_RECIPES";
export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const GET_RECIPE_INGREDIENTS = "GET_RECIPE_INGREDIENTS";
